//@version=5
indicator("Money Printer Go BRRRRRR")
import sourdiesel1202/MPB/7 as mpb
// drawVerticalLine(offset,color) =>
    // line.new(bar_index[offset], low-LineLength, bar_index[offset], high+LineLength, color=color.new(color.yellow, 50), width=3)
// adx_lookback=input(4, "ADX Lookback")
// trend_lookback=input(1,"Trend Lookback")

// obv_percent = input(5, "OBV Percent")
trend_lookback=input(1,"Trend Lookback")

// obv_percent =
_adx = input(14,"ADX Value")
// debug = input(true, "Debug", "Enable Logging")
// [prior_dmilpus, prior_dmineg, prior_adx] = ta.dmi(14, 14)

//[macdLine, signalLine, histLine] = ta.macd(close, fastInput, slowInput, 9)
// obv = ta.obv
// prior_obv = ta.obv[1]
_dmiplus = input(17, "DMI+ Signal")
_dmineg = input(17, "DMI- Signal")
dmi_delta = input(1, "DMI Delta")
dmi_rapid=input(5, "DMI Rapid Change", "The delta between DMI[1] and DMI. If this value is exceeded, flag reversal")
adx_rapid=input(0.5, "ADX Rapid Change", "The delta between ADX[1] and ADX. If this value is exceeded, flag reversal")
xxs_mpb_value=1
xs_mpb_value=3
s_mpb_value=5
m_mpb_value=8
l_mpb_value=12
xl_mpb_value=15
xxl_mpb_value=20


[mpb_dmi] = mpb.calculate_dmi_value(dmi_delta,_dmiplus, _dmineg,dmi_rapid)
[mpb_adx] = mpb.calculate_adx_value()
[mpb_macd]=mpb.calculate_macd_value()
[mpb_obv]= mpb.calculate_obv_value(0.01)
[mpb_sma, fast_sma, slow_sma, _close, _open]= mpb.calculate_sma_value()
// if debug
plotchar(mpb_macd, "MPB MACD Value", "", location = location.top)
plotchar(mpb_obv, "MPB OBV Value", "", location = location.top)
plotchar(mpb_adx, "MPB ADX Value", "", location = location.top)
plotchar(mpb_dmi, "MPB DMI Value", "", location = location.top)
plotchar(mpb_sma, "MPB SMA Value", "", location = location.top)
plotchar(_open, "Open Value", "", location = location.top)
plotchar(_close, "Close Value", "", location = location.top)
plotchar(slow_sma, "Slow SMA Value", "", location = location.top)
plotchar(fast_sma, "Fast SMA Value", "", location = location.top)
// obv = ta.obv

// value = mpb_adx+mpb_dmi+mpb_macd+mpb_obv
value = mpb_sma+mpb_adx+mpb_dmi+mpb_macd+mpb_obv
old_value = mpb_sma[1]+mpb_adx[1]+mpb_dmi[1]+mpb_macd[1]+mpb_obv[1]


plot(0, color = color.purple)
plot(100, color = color.purple)
plot(-100, color = color.purple)
plot(value, color = color.blue)
// plot(mpb_macd, color = color.yellow)
// plot(mpb_adx, color = color.white)
// plot(mpb_obv, color = color.green)
// plot(mpb_dmi, color = color.white)
// plot(mpb_adx, color = color.yellow)
//pl//ot(signalLine, color = color.orange)
